import os


VERY_HIGH_INCOME_THRESHOLD = 1_000_000
LOAN_TO_INCOME_MULTIPLIER_ALERT = 1.5
DTI_MEDIUM_THRESHOLD = 43.0

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")
EXPLANATION_MODEL = os.getenv("EXPLANATION_MODEL", "gpt-4o-mini")
EXPLANATION_TIMEOUT_SECONDS = float(os.getenv("EXPLANATION_TIMEOUT_SECONDS", "20"))
